### ISSUE TITLE
Unitialized constant by rendering .rux from .html.erb template

### ISSUE THREAD

**Issue by serhiijun** [camertron/rux#4]
<img width="349" alt="image" src="https://user-images.githubusercontent.com/31795690/233836020-08e84463-cd26-46af-8e43-d881a7554bc5.png">

```ruby
#app/components/ui/buttons/red_button_component/red_button_component.rux
class Ui::Buttons::RedButtonComponent::RedButtonComponent < ViewComponent::Base
  def initialize
  end

  def call
    <div>button</div>
  end
end
```

```erb
<!--erb template in another simple view component (not rux) -->
  <%= render Ui::Buttons::RedButtonComponent::RedButtonComponent.new(), layout: false %>
```

<img width="733" alt="image" src="https://user-images.githubusercontent.com/31795690/233836106-b8816701-8286-4bed-8321-b00e3c41a17c.png">

**Comment by serhiijun** [comment]
@camertron bump👆

**Comment by camertron** [comment]
Hey @serhiijun, thanks for reaching out about this. Unfortunately I haven't been able to reproduce it in my rux test app. It would help a great deal if you could put together your own test app that demonstrates the problem. It would also help if you could tell me:

1. Your ruby version
2. Your rails version
3. If you're using Zeitwerk
4. If the `RedButtonComponent` lives in a Rails engine

**Comment by serhiijun** [comment]
@camertron please check this demo repo https://github.com/serhiijun/rails_rux_demo

Uncomment this line, please, to reproduce an issue https://github.com/serhiijun/rails_rux_demo/blob/main/app/components/ui/bentries/home_component/home_component.html.erb#L3

**Comment by camertron** [comment]
Hey @serhiijun, thanks for the demo repo, that was really helpful! I see two issues at play here:

1. It looks like your Gemfile contains the rux gem, but not rux-rails. All the logic that makes auto-compilation and hot reloading possible are in rux-rails, so you'll need to add it to your Gemfile instead of rux itself.
2. I just discovered that an update to Zeitwerk caused a small bug in rux-rails versions 1.2.1 and earlier, so please make sure you use rux-rails 1.2.2, published about 5 minutes ago.

**Comment by serhiijun** [comment]
@camertron thank you a lot! Now that works, really cool!🎉 I'm sure this is a new way we need to code our rails components!

**Comment by camertron** [comment]
Awesome, glad it's working for you! 😄
